// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_rolling_stone = "CgkI6M2W0bwfEAIQBw"; // <GPGSID>
        public const string achievement_first_try = "CgkI6M2W0bwfEAIQAA"; // <GPGSID>
        public const string achievement_the_floor_is_lava = "CgkI6M2W0bwfEAIQDg"; // <GPGSID>
        public const string achievement_paper_knight = "CgkI6M2W0bwfEAIQAQ"; // <GPGSID>
        public const string achievement_i_did_it_for_the_achievement = "CgkI6M2W0bwfEAIQDQ"; // <GPGSID>
        public const string achievement_spider_man = "CgkI6M2W0bwfEAIQCQ"; // <GPGSID>
        public const string achievement_writer = "CgkI6M2W0bwfEAIQEQ"; // <GPGSID>
        public const string achievement_better_luck_next_time = "CgkI6M2W0bwfEAIQBA"; // <GPGSID>
        public const string achievement_you_still_there = "CgkI6M2W0bwfEAIQDw"; // <GPGSID>
        public const string achievement_paper_king = "CgkI6M2W0bwfEAIQAg"; // <GPGSID>
        public const string achievement_paper_god = "CgkI6M2W0bwfEAIQAw"; // <GPGSID>
        public const string achievement_sticky_sticky = "CgkI6M2W0bwfEAIQCA"; // <GPGSID>
        public const string achievement_the_wheight_of_words = "CgkI6M2W0bwfEAIQEA"; // <GPGSID>
        public const string achievement_playwright = "CgkI6M2W0bwfEAIQEg"; // <GPGSID>
        public const string achievement_the_key_of_success = "CgkI6M2W0bwfEAIQDA"; // <GPGSID>
        public const string achievement_really = "CgkI6M2W0bwfEAIQCw"; // <GPGSID>
        public const string achievement_perseverance = "CgkI6M2W0bwfEAIQBQ"; // <GPGSID>
        public const string achievement_maniac = "CgkI6M2W0bwfEAIQCg"; // <GPGSID>
        public const string achievement_ragequit = "CgkI6M2W0bwfEAIQBg"; // <GPGSID>
        public const string achievement_i_did_it = "CgkI6M2W0bwfEAIQEw"; // <GPGSID>

}

